name: flutter_sample_melos_common
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1
  roggle: ^0.3.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.4.0

flutter_gen:
  output: lib/src/gen/

flutter:
  uses-material-design: true
  assets:
    - assets/common/images/
