name: flutter_sample_melos

repository: https://github.com/susatthi/flutter-sample-melos

sdkPath: .fvm/flutter_sdk

packages:
  - packages/*

scripts:
  get-dependencies:
    exec: fvm flutter pub get
  clean:
    exec: fvm flutter clean
  analyze:
    exec: fvm flutter analyze
  format:
    exec: fvm dart format lib/
  format-dry-exit-if-changed:
    exec: fvm dart format --dry-run --set-exit-if-changed lib/
  build-runner:
    exec: fvm flutter pub run build_runner build --delete-conflicting-outputs
